#include "emvTagList.h"
#include "hashtable.h"

void emvInit(dict_t *hashtab[HASHSIZE])
{
	addItem("9F01", "Acquirer Identifier", hashtab);
	addItem("9F40", "Additional Terminal Capabilities", hashtab);
	addItem("81", "Amount, Authorised(Binary)", hashtab);
	addItem("9F02", "Amount, Authorised(Numeric)", hashtab);
	addItem("9F04", "Amount, Other(Binary)", hashtab);
	addItem("9F03", "Amount, Other(Numeric)", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("", "", hashtab);
	addItem("6F", "File Control Information(FCI) Template", hashtab);
	addItem("9F4C", "ICC Dynamic Number", hashtab);
}